routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::resource('assurances', 'AssuranceController');
    Route::resource('diagnostics', 'DiagnosticController');
    Route::resource('docteurs', 'DocteurController');
    Route::resource('enfants', 'EnfantController');
    Route::resource('prises', 'PriseController');
    Route::resource('services', 'ServiceController');
    Route::resource('tuteurs', 'TuteurController');
    Route::resource('rapports', 'RapportController');
    Route::resource('rdvs', 'RdvController');

    Route::group(['prefix' => 'prises/{prise}'], function () {
        Route::get('generatePdf', 'PriseController@generatePdf')->name('prises.generatePdf');
    });

    Route::post('rapports/generatePdfPerDate', 'RapportController@generatePdfPerDate')->name('rapports.generatePdfPerDate');

    Route::group(['prefix' => 'enfants/{enfant}'], function () {
        Route::get('prises', 'EnfantController@showPrises')->name('enfants.showPrises');
        Route::get('generatePrises', 'EnfantController@generatePrises')->name('enfants.generatePrises');
        Route::get('generateRapports', 'EnfantController@generateRapports')->name('enfants.generateRapports');
        Route::get('generateRapport/{date}', 'EnfantController@generateRapport')->name('enfants.generateRapport');
    });

    Route::group(['prefix' => 'rdvs'], function () {
        Route::get('enfant/{enfant}', 'RdvController@showEnfantRdv')->name('rdvs.showEnfantRdv');
        Route::get('assistant/{user}', 'RdvController@showUserRdv')->name('rdvs.showUserRdv');
    });

    Route::get('rapports/{rapport}/duplicate', 'RapportController@duplicate')->name('rapports.duplicate');
});

app/Tuteur.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Tuteur
 *
 * @property int $id
 * @property string $firstname
 * @property string $lastname
 * @property string $type
 * @property string|null $email
 * @property string|null $phone
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Enfant[] $enfants
 * @property-read int|null $enfants_count
 * @property-read mixed $fullname
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur whereFirstname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur whereLastname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur wherePhone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tuteur whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Tuteur extends Model
{
    protected $fillable = [
        'firstname', 'lastname', 'type', 'email', 'phone',
    ];

    public function getFullnameAttribute($value)
    {
        return ucfirst($this->firstname) . ' ' . ucfirst($this->lastname);
    }

    public function enfants()
    {
        return $this->belongsToMany('App\Enfant');
    }

    public function delete()
    {
        $this->enfants()->detach();
        parent::delete();
    }
}

app/Http/Controllers/TuteurController.php
<?php

namespace App\Http\Controllers;

use App\Tuteur;
use Illuminate\Http\Request;

class TuteurController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('tuteur.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('tuteur.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $rules = [
            'firstname' => 'required',
            'lastname' => 'required',
            'type' => 'required|in:Père,Mère,Autre',
            'email' => 'email',
        ];
        $request->validate($rules);
        $tuteur = new Tuteur($request->all());
        $tuteur->save();
        $tuteur->enfants()->sync($request->enfants);
        return redirect()->route('tuteurs.index')->with('success', __('Tuteur ajouté'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tuteur  $tuteur
     *
     * @return \Illuminate\View\View
     */
    public function show(Tuteur $tuteur)
    {
        return view('tuteur.show', ['tuteur' => $tuteur]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tuteur  $tuteur
     *
     * @return \Illuminate\View\View
     */
    public function edit(Tuteur $tuteur)
    {
        return view('tuteur.edit', ['tuteur' => $tuteur]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tuteur  $tuteur
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Tuteur $tuteur)
    {
        $rules = [
            'firstname' => 'required',
            'lastname' => 'required',
            'type' => 'required|in:Père,Mère,Autre',
            'email' => 'email',
        ];
        $request->validate($rules);
        $tuteur->update($request->all());
        $tuteur->enfants()->sync($request->enfants);
        return redirect()->route('tuteurs.index')->with('success', __('Tuteur mis à jour'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tuteur  $tuteur
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Tuteur $tuteur)
    {
        $tuteur->delete();
        return redirect()->route('tuteurs.index')->with('success', __('Tuteur supprimé'));
    }
}

resources/views/tuteur/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Nouveau tuteur') }}</div>

                <div class="card-body">
                    {{ Form::open([ 'method'  => 'POST', 'route' => [ 'tuteurs.store' ], 'autocomplete' => 'off', 'files' => true ]) }}
                    <div class="form-group">
                        {!! Form::label('firstname', __('Prénom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('firstname', null, ['class' => 'form-control'.($errors->has('firstname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('firstname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('firstname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('lastname', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('lastname', null, ['class' => 'form-control'.($errors->has('lastname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('lastname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('lastname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('type', __('Type'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('type', ['Père' => __('Père'), 'Mère' => __('Mère'), 'Autre' => __('Autre')], Null, ['class' => 'form-control'.($errors->has('type') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('type'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('type') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('email', __('Email'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::email('email', null, ['class' => 'form-control'.($errors->has('email') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('email'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('email') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone', __('Phone'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('phone', null, ['class' => 'form-control'.($errors->has('phone') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('phone'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('phone') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('enfants', __('Enfants'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('enfants[]', App\Enfant::all(['id', 'firstname', 'lastname'])->pluck('fullname', 'id'), Null, ['class' => 'tags form-control'.($errors->has('enfants') ? ' is-invalid' : ''), 'multiple' => 'multiple']) !!}
                        @if ($errors->has('enfants'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('enfants') !!}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        {!! Form::submit(__('Valider'), ['class' => 'btn btn-success']) !!}
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tuteur/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ $tuteur->fullname }}</div>

                <div class="card-body">
                    {{ Form::open([ 'method'  => 'patch', 'route' => [ 'tuteurs.update', $tuteur->id ], 'autocomplete' => 'off', 'files' => true ]) }}
                    <div class="form-group">
                        {!! Form::label('firstname', __('Prénom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('firstname', $tuteur->firstname, ['class' => 'form-control'.($errors->has('firstname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('firstname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('firstname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('lastname', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('lastname', $tuteur->lastname, ['class' => 'form-control'.($errors->has('lastname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('lastname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('lastname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('type', __('Type'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('type', ['Père' => __('Père'), 'Mère' => __('Mère'), 'Autre' => __('Autre')], $tuteur->type, ['class' => 'form-control'.($errors->has('type') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('type'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('type') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('email', __('Email'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::email('email', $tuteur->email, ['class' => 'form-control'.($errors->has('email') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('email'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('email') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone', __('Phone'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('phone', $tuteur->phone, ['class' => 'form-control'.($errors->has('phone') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('phone'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('phone') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('enfants', __('Enfants'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('enfants[]', App\Enfant::all(['id', 'firstname', 'lastname'])->pluck('fullname', 'id'), $tuteur->enfants, ['class' => 'tags form-control'.($errors->has('enfants') ? ' is-invalid' : ''), 'multiple' => 'multiple']) !!}
                        @if ($errors->has('enfants'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('enfants') !!}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        {!! Form::submit(__('Valider'), ['class' => 'btn btn-success']) !!}
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tuteur/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {{ __('Tuteurs') }}
                    <a class="btn btn-primary float-sm-right" href="{{route('tuteurs.create')}}" role="button">{{__('Ajouter')}}</a>
                </div>

                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>{{ __('Nom') }}</th>
                                <th>{{ __('Prénom') }}</th>
                                <th>{{ __('Type') }}</th>
                                <th>{{ __('Email') }}</th>
                                <th>{{ __('Phone') }}</th>
                                <th>{{ __('Enfants') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(App\Tuteur::all() as $tuteur)
                            <tr>
                                <td>{{ $tuteur->lastname }}</td>
                                <td>{{ $tuteur->firstname }}</td>
                                <td>{{ __($tuteur->type) }}</td>
                                <td>{{ $tuteur->email }}</td>
                                <td>{{ $tuteur->phone }}</td>
                                <td>
                                    @foreach($tuteur->enfants as $enfant)
                                    <span class="badge badge-light">{{ $enfant->fullname }}</span>
                                    @endforeach
                                </td>
                                <td>
                                    <div class="dropdown float-right">
                                        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton{{$tuteur->id}}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ __('Actions') }}
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton{{$tuteur->id}}">
                                            <a class="dropdown-item" href="{{route('tuteurs.show', $tuteur->id)}}">{{__('Voir')}}</a>
                                            <a class="dropdown-item" href="{{route('tuteurs.edit', $tuteur->id)}}">{{__('Modifier')}}</a>
                                            {{ Form::open([ 'method'  => 'delete', 'route' => [ 'tuteurs.destroy', $tuteur->id ] ]) }}
                                            <a class="dropdown-item delete-model" href="javascript:void(0)">{{__('Supprimer')}}</a>
                                            {{ Form::close() }}
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tuteur/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ $tuteur->fullname }}</div>

                <div class="card-body">
                    <div class="form-group">
                        {!! Form::label('firstname', __('Prénom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('firstname', $tuteur->firstname, ['class' => 'form-control'.($errors->has('firstname') ? ' is-invalid' : ''), 'readonly' => 'readonly']) !!}
                        @if ($errors->has('firstname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('firstname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('lastname', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('lastname', $tuteur->lastname, ['class' => 'form-control'.($errors->has('lastname') ? ' is-invalid' : ''), 'readonly' => 'readonly']) !!}
                        @if ($errors->has('lastname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('lastname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('type', __('Type'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('type', ['Père' => __('Père'), 'Mère' => __('Mère'), 'Autre' => __('Autre')], $tuteur->type, ['class' => 'form-control'.($errors->has('type') ? ' is-invalid' : ''), 'disabled' => 'disabled']) !!}
                        @if ($errors->has('type'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('type') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('email', __('Email'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::email('email', $tuteur->email, ['class' => 'form-control'.($errors->has('email') ? ' is-invalid' : ''), 'readonly' => 'readonly']) !!}
                        @if ($errors->has('email'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('email') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone', __('Phone'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('phone', $tuteur->phone, ['class' => 'form-control'.($errors->has('phone') ? ' is-invalid' : ''), 'readonly' => 'readonly']) !!}
                        @if ($errors->has('phone'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('phone') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('enfants', __('Enfants'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::select('enfants[]', App\Enfant::all(['id', 'firstname', 'lastname'])->pluck('fullname', 'id'), $tuteur->enfants, ['class' => 'tags form-control'.($errors->has('enfants') ? ' is-invalid' : ''), 'multiple' => 'multiple', 'disabled' => 'disabled']) !!}
                        @if ($errors->has('enfants'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('enfants') !!}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection