routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::resource('assurances', 'AssuranceController');
    Route::resource('diagnostics', 'DiagnosticController');
    Route::resource('docteurs', 'DocteurController');
    Route::resource('enfants', 'EnfantController');
    Route::resource('prises', 'PriseController');
    Route::resource('services', 'ServiceController');
    Route::resource('tuteurs', 'TuteurController');
    Route::resource('rapports', 'RapportController');
    Route::resource('rdvs', 'RdvController');

    Route::group(['prefix' => 'prises/{prise}'], function () {
        Route::get('generatePdf', 'PriseController@generatePdf')->name('prises.generatePdf');
    });

    Route::post('rapports/generatePdfPerDate', 'RapportController@generatePdfPerDate')->name('rapports.generatePdfPerDate');

    Route::group(['prefix' => 'enfants/{enfant}'], function () {
        Route::get('prises', 'EnfantController@showPrises')->name('enfants.showPrises');
        Route::get('generatePrises', 'EnfantController@generatePrises')->name('enfants.generatePrises');
        Route::get('generateRapports', 'EnfantController@generateRapports')->name('enfants.generateRapports');
        Route::get('generateRapport/{date}', 'EnfantController@generateRapport')->name('enfants.generateRapport');
    });

    Route::group(['prefix' => 'rdvs'], function () {
        Route::get('enfant/{enfant}', 'RdvController@showEnfantRdv')->name('rdvs.showEnfantRdv');
        Route::get('assistant/{user}', 'RdvController@showUserRdv')->name('rdvs.showUserRdv');
    });

    Route::get('rapports/{rapport}/duplicate', 'RapportController@duplicate')->name('rapports.duplicate');
});

app/Assurance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Assurance
 *
 * @property int $id
 * @property string $name
 * @property string $fullname
 * @property string $shortname
 * @property string|null $desc
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Enfant[] $enfants
 * @property-read int|null $enfants_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Prise[] $prises
 * @property-read int|null $prises_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance whereDesc($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance whereFullname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance whereShortname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Assurance whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Assurance extends Model
{
    protected $fillable = [
        'name', 'fullname', 'shortname', 'desc',
    ];

    public function enfants()
    {
        return $this->belongsToMany('App\Enfant');
    }

    public function prises()
    {
        return $this->hasMany('App\Prise');
    }
}

app/Http/Controllers/AssuranceController.php
<?php

namespace App\Http\Controllers;

use App\Assurance;
use Illuminate\Http\Request;

class AssuranceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('assurance.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('assurance.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'fullname' => 'required',
            'shortname' => 'required',
        ];
        $request->validate($rules);
        $assurance = new Assurance($request->all());
        $assurance->save();
        return redirect()->route('assurances.index')->with('success', __('Assurance ajoutée'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Assurance  $assurance
     *
     * @return \Illuminate\View\View
     */
    public function show(Assurance $assurance)
    {
        return view('assurance.show', ['assurance' => $assurance]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Assurance  $assurance
     *
     * @return \Illuminate\View\View
     */
    public function edit(Assurance $assurance)
    {
        if ($assurance->id === 1) {
            abort(404);
        }
        return view('assurance.edit', ['assurance' => $assurance]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Assurance  $assurance
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Assurance $assurance)
    {
        if ($assurance->id === 1) {
            abort(404);
        }
        $rules = [
            'name' => 'required',
            'fullname' => 'required',
            'shortname' => 'required',
        ];
        $request->validate($rules);
        $assurance->update($request->all());
        return redirect()->route('assurances.index')->with('success', __('Assurance mise à jour'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Assurance  $assurance
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Assurance $assurance)
    {
        if ($assurance->id === 1) {
            abort(404);
        }
        $assurance->delete();
        return redirect()->route('assurances.index')->with('success', __('Assurance supprimée'));
    }
}

resources/views/assurance/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Nouvelle assurance') }}</div>

                <div class="card-body">
                    {{ Form::open([ 'method'  => 'POST', 'route' => [ 'assurances.store' ], 'autocomplete' => 'off', 'files' => true ]) }}
                    <div class="form-group">
                        {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('name', null, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('name') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('fullname', __('Nom complet'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('fullname', null, ['class' => 'form-control'.($errors->has('fullname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('fullname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('fullname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('shortname', __('Nom racourci'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('shortname', null, ['class' => 'form-control'.($errors->has('shortname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('shortname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('shortname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    
                    <div class="form-group">
                        {!! Form::submit(__('Valider'), ['class' => 'btn btn-success']) !!}
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/assurance/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ $assurance->name }}</div>

                <div class="card-body">
                    {{ Form::open([ 'method'  => 'patch', 'route' => [ 'assurances.update', $assurance->id ], 'autocomplete' => 'off', 'files' => true ]) }}
                    <div class="form-group">
                        {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('name', $assurance->name, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('name') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('fullname', __('Nom complet'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('fullname', $assurance->fullname, ['class' => 'form-control'.($errors->has('fullname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('fullname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('fullname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('shortname', __('Nom racourci'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('shortname', $assurance->shortname, ['class' => 'form-control'.($errors->has('shortname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('shortname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('shortname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    
                    <div class="form-group">
                        {!! Form::submit(__('Valider'), ['class' => 'btn btn-success']) !!}
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/assurance/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {{ __('Assurances') }}
                    <a class="btn btn-primary float-sm-right" href="{{route('assurances.create')}}" role="button">{{__('Ajouter')}}</a>
                </div>

                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>{{ __('Nom') }}</th>
                                <th>{{ __('Nom complet') }}</th>
                                <th>{{ __('Nom racourci') }}</th>
                                <th>{{ __('Nombre d\'enfants') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(App\Assurance::all() as $assurance)
                            <tr>
                                <td>{{ $assurance->name }}</td>
                                <td>{{ $assurance->fullname }}</td>
                                <td>{{ $assurance->shortname }}</td>
                                <td>{{ $assurance->enfants()->count() }}</td>
                                <td>
                                    <div class="dropdown float-right">
                                        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton{{$assurance->id}}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ __('Actions') }}
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton{{$assurance->id}}">
                                            <a class="dropdown-item" href="{{route('assurances.show', $assurance->id)}}">{{__('Voir')}}</a>
                                            @if($assurance->id > 1)
                                            <a class="dropdown-item" href="{{route('assurances.edit', $assurance->id)}}">{{__('Modifier')}}</a>
                                            {{ Form::open([ 'method'  => 'delete', 'route' => [ 'assurances.destroy', $assurance->id ] ]) }}
                                            <a class="dropdown-item delete-model" href="javascript:void(0)">{{__('Supprimer')}}</a>
                                            {{ Form::close() }}
                                            @endif
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/assurance/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ $assurance->name }}</div>
                <div class="card-body">
                    <div class="form-group">
                        {!! Form::label('name', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('name', $assurance->name, ['class' => 'form-control'.($errors->has('name') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('name') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('fullname', __('Nom complet'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('fullname', $assurance->fullname, ['class' => 'form-control'.($errors->has('fullname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('fullname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('fullname') !!}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('shortname', __('Nom racourci'), ['class' => 'col-form-label text-md-right']) !!}
                        {!! Form::text('shortname', $assurance->shortname, ['class' => 'form-control'.($errors->has('shortname') ? ' is-invalid' : '')]) !!}
                        @if ($errors->has('shortname'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{!! $errors->first('shortname') !!}</strong>
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection