routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::resource('assurances', 'AssuranceController');
    Route::resource('diagnostics', 'DiagnosticController');
    Route::resource('docteurs', 'DocteurController');
    Route::resource('enfants', 'EnfantController');
    Route::resource('prises', 'PriseController');
    Route::resource('services', 'ServiceController');
    Route::resource('tuteurs', 'TuteurController');
    Route::resource('rapports', 'RapportController');
    Route::resource('rdvs', 'RdvController');

    Route::group(['prefix' => 'prises/{prise}'], function () {
        Route::get('generatePdf', 'PriseController@generatePdf')->name('prises.generatePdf');
    });

    Route::post('rapports/generatePdfPerDate', 'RapportController@generatePdfPerDate')->name('rapports.generatePdfPerDate');

    Route::group(['prefix' => 'enfants/{enfant}'], function () {
        Route::get('prises', 'EnfantController@showPrises')->name('enfants.showPrises');
        Route::get('generatePrises', 'EnfantController@generatePrises')->name('enfants.generatePrises');
        Route::get('generateRapports', 'EnfantController@generateRapports')->name('enfants.generateRapports');
        Route::get('generateRapport/{date}', 'EnfantController@generateRapport')->name('enfants.generateRapport');
    });

    Route::group(['prefix' => 'rdvs'], function () {
        Route::get('enfant/{enfant}', 'RdvController@showEnfantRdv')->name('rdvs.showEnfantRdv');
        Route::get('assistant/{user}', 'RdvController@showUserRdv')->name('rdvs.showUserRdv');
    });

    Route::get('rapports/{rapport}/duplicate', 'RapportController@duplicate')->name('rapports.duplicate');
});

app/Enfant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Enfant
 *
 * @property int $id
 * @property string $firstname
 * @property string $lastname
 * @property string $gender
 * @property string $birthdate
 * @property string|null $remarque
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property int $diagnostic_id
 * @property int $docteur_id
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Assistant[] $assistants
 * @property-read int|null $assistants_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Assurance[] $assurances
 * @property-read int|null $assurances_count
 * @property-read \App\Diagnostic $diagnostic
 * @property-read \App\Docteur $docteur
 * @property-read mixed $fullname
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Prise[] $prises
 * @property-read int|null $prises_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Service[] $services
 * @property-read int|null $services_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Tuteur[] $tuteurs
 * @property-read int|null $tuteurs_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereBirthdate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereDiagnosticId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereDocteurId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereFirstname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereGender($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereLastname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereRemarque($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Enfant whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Enfant extends Model
{
    protected $fillable = [
        'firstname', 'lastname', 'gender', 'birthdate', 'remarque', 'diagnostic_id', 'docteur_id', 'anamnese',
    ];

    protected $appends = [
        'fullname',
    ];

    public function getFullnameAttribute($value)
    {
        return ucfirst($this->firstname) . ' ' . strtoupper($this->lastname);
    }

    public function assurances()
    {
        return $this->belongsToMany('App\Assurance');
    }

    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    public function diagnostic()
    {
        return $this->belongsTo('App\Diagnostic');
    }

    public function docteur()
    {
        return $this->belongsTo('App\Docteur');
    }

    public function tuteurs()
    {
        return $this->belongsToMany('App\Tuteur');
    }

    public function prises()
    {
        return $this->hasMany('App\Prise');
    }

    public function rapports()
    {
        return $this->hasMany('App\Rapport');
    }

    public function rdvs()
    {
        return $this->hasMany('App\Rdv');
    }

    public function delete()
    {
        $this->assurances()->detach();
        $this->users()->detach();
        $this->tuteurs()->detach();
        $this->prises()->delete();
        $this->rapports()->delete();
        $this->rdvs()->delete();
        parent::delete();
    }
}

app/Http/Controllers/EnfantController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\User;
use App\Prise;
use App\Enfant;
use App\Tuteur;
use App\Docteur;
use App\Rapport;
use App\Service;
use App\Assistant;
use App\Assurance;
use Carbon\Carbon;
use App\Diagnostic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class EnfantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        if (auth()->user()->isAdmin()) {
            $enfants = new Enfant;
        } else {
            $enfants = auth()->user()->enfants();
        }
        $perPage = request()->has('perPage') ? request('perPage') : 10;
        $queries = ['perPage' => $perPage];
        $users = User::assistant()->get();
        $userArray = [];
        foreach($users as $user) {
            $userArray[$user->id] = $user->name . ' (' . $user->service->name . ')';
        }
        $filterByUser = ['' => 'Filtrer par Utilisateur'] + $userArray;
        $filterByAssurance = ['' => 'Filtrer par assurance'] + Assurance::all(['name', 'id'])->pluck('name', 'id')->toArray();
        $orderBy = [
            '' => 'Trier par',
            'firstname' => 'Prénom',
            'lastname' => 'Nom',
            'birthdate' => 'Date de naissance',
        ];

        // Filter By user
        if (request()->has('user') && request('user')) {
            // $enfants = $enfants->where($column, request('user'));
            $user = request('user');
            $enfants = $enfants->whereHas('users', function ($query) use ($user) {
                $query->where('user_id', $user);
            });
            $queries['user'] = request('user');
        }

        // Filter By Assurance
        if (request()->has('assurance') && request('assurance')) {
            // $enfants = $enfants->where($column, request('service'));
            $assurance = request('assurance');
            $enfants = $enfants->whereHas('assurances', function ($query) use ($assurance) {
                $query->where('assurance_id', $assurance);
            });
            $queries['assurance'] = request('assurance');
        }

        // Order By
        if (request()->has('orderBy') && request()->has('sort') && request('orderBy') && request('sort')) {
            $enfants = $enfants->orderBy(request('orderBy'), request('sort'));
            $queries['orderBy'] = request('orderBy');
            $queries['sort'] = request('sort');
        } else {
            $enfants = $enfants->orderBy('firstname', 'asc')->orderBy('lastname', 'asc');
        }

        $enfants = $enfants->paginate($perPage)->appends($queries);

        return view('enfant.index', compact('enfants', 'filterByUser', 'filterByAssurance', 'orderBy', 'perPage'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $users = User::assistant()->get();
        $usersArray = [];
        foreach($users as $user) {
            $usersArray[$user->id] = $user->name . ' (' . $user->service->name . ')';
        }
        return view('enfant.create', compact('usersArray'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $rules = [
            'firstname' => 'required',
            'lastname' => 'required',
            'gender' => 'required|in:male,female',
            'birthdate' => 'required|date',
        ];
        $request->validate($rules);
        $postRequest = $request->all();
        if (substr($postRequest['diagnostic_id'], 0, 4) == 'new:') {
            $newDiagnostic = Diagnostic::create(['name' => substr($postRequest['diagnostic_id'], 4)]);
            $postRequest['diagnostic_id'] = $newDiagnostic->id;
        }
        if (substr($postRequest['docteur_id'], 0, 4) == 'new:') {
            $newDocteur = Docteur::create(['name' => substr($postRequest['docteur_id'], 4), 'diagnostic_id' => $postRequest['diagnostic_id']]);
            $postRequest['docteur_id'] = $newDocteur->id;
        }

        $enfant = new Enfant($postRequest);
        $enfant->save();
        $tuteursIds = $usersIds = $assurancesIds = [];

        // Tuteurs
        if ($request->has('tuteurs')) {
            foreach ($request->tuteurs as $tagId) {
                if (substr($tagId, 0, 4) == 'new:') {
                    $name = explode(' ', substr($tagId, 4));
                    $firstname = array_key_exists(0, $name) ? $name[0] : '';
                    $lastname = array_key_exists(1, $name) ? $name[1] : '';
                    $newTag = Tuteur::create(['firstname' => $firstname, 'lastname' => $lastname, 'type' => 'Autre']);
                    $tuteursIds[] = $newTag->id;
                    continue;
                }
                $tuteursIds[] = $tagId;
            }
        }

        // Assistants
        if ($request->has('users')) {
            foreach ($request->users as $tagId) {
                $usersIds[] = $tagId;
            }
        }

        // Assurances
        if ($request->has('assurances')) {
            foreach ($request->assurances as $tagId) {
                if (substr($tagId, 0, 4) == 'new:') {
                    $newTag = Assurance::create(['name' => substr($tagId, 4), 'fullname' => substr($tagId, 4), 'shortname' => substr($tagId, 4)]);
                    $assurancesIds[] = $newTag->id;
                    continue;
                }
                $assurancesIds[] = $tagId;
            }
        }

        $enfant->tuteurs()->sync($tuteursIds);
        $enfant->users()->sync($usersIds);
        $enfant->assurances()->sync($assurancesIds);
        $data = [];
        if ($request->has('code')) {
            foreach ($request->code as $key => $code) {
                if ($code) {
                    $date = $request->date[$key];
                    $charge = $request->charge[$key];
                    $assurance = $request->assurance[$key];
                    $data[] = [
                        'code' => $code,
                        'date' => $date,
                        'charge' => $charge,
                        'enfant_id' => $enfant->id,
                        'assurance_id' => $assurance,
                        'created_at' => \Carbon\Carbon::now(),
                        'updated_at' => \Carbon\Carbon::now(),
                    ];
                }
            }
        }
        $prises = new Prise();
        $prises->insert($data);
        return redirect()->route('enfants.index')->with('success', __('Enfant ajouté'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Enfant  $enfant
     *
     * @return \Illuminate\View\View
     */
    public function show(Enfant $enfant)
    {
        $users = User::assistant()->get();
        $usersArray = [];
        foreach($users as $user) {
            $usersArray[$user->id] = $user->name . ' (' . $user->service->name . ')';
        }
        return view('enfant.show', compact('enfant', 'usersArray'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Enfant  $enfant
     *
     * @return \Illuminate\View\View
     */
    public function edit(Enfant $enfant)
    {
        $users = User::assistant()->get();
        $usersArray = [];
        foreach($users as $user) {
            $usersArray[$user->id] = $user->name . ' (' . $user->service->name . ')';
        }
        return view('enfant.edit', compact('enfant', 'usersArray'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Enfant  $enfant
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Enfant $enfant)
    {
        if (auth()->user()->isAssistant()) {
            $data = $request->only(['anamnese']);
            $enfant->update($data);
            return redirect()->route('enfants.index')->with('success', __('Enfant mis à jour'));
        }
        $rules = [
            'firstname' => 'required',
            'lastname' => 'required',
            'gender' => 'required|in:male,female',
            'birthdate' => 'required|date',
        ];
        $request->validate($rules);

        $postRequest = $request->all();
        if (substr($postRequest['diagnostic_id'], 0, 4) == 'new:') {
            $newDiagnostic = Diagnostic::create(['name' => substr($postRequest['diagnostic_id'], 4)]);
            $postRequest['diagnostic_id'] = $newDiagnostic->id;
        }
        if (substr($postRequest['docteur_id'], 0, 4) == 'new:') {
            $newDocteur = Docteur::create(['name' => substr($postRequest['docteur_id'], 4), 'diagnostic_id' => $postRequest['diagnostic_id']]);
            $postRequest['docteur_id'] = $newDocteur->id;
        }

        $enfant->update($postRequest);
        $tuteursIds = $usersIds = $assurancesIds = [];

        // Tuteurs
        if ($request->has('tuteurs')) {
            foreach ($request->tuteurs as $tagId) {
                if (substr($tagId, 0, 4) == 'new:') {
                    $name = explode(' ', substr($tagId, 4));
                    $firstname = array_key_exists(0, $name) ? $name[0] : '';
                    $lastname = array_key_exists(1, $name) ? $name[1] : '';
                    $newTag = Tuteur::create(['firstname' => $firstname, 'lastname' => $lastname, 'type' => 'Autre']);
                    $tuteursIds[] = $newTag->id;
                    continue;
                }
                $tuteursIds[] = $tagId;
            }
        }

        // Users
        if ($request->has('users')) {
            foreach ($request->users as $tagId) {
                $usersIds[] = $tagId;
            }
        }

        // Assurances

resources/views/enfant/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {{ __('Enfants') }}
                    @if(auth()->user()->isAdmin())
                    <a class="btn btn-primary float-sm-right" href="{{route('enfants.create')}}" role="button">{{__('Ajouter')}}</a>
                    @endif
                </div>

                <div class="card-body">
                    @component('components.exportrapports')@endcomponent
                    @component('components.filters.enfants', compact('orderBy', 'filterByUser', 'filterByAssurance', 'perPage'))@endcomponent
                    <table class="table">
                        <thead>
                            <tr>
                                <th>{{ __('Nom') }}</th>
                                <th>{{ __('Prénom') }}</th>
                                <th>{{ __('Sexe') }}</th>
                                <th>{{ __('Date de naissance') }}</th>
                                <th>{{ __('Tuteurs') }}</th>
                                <th>{{ __('Assistants') }}</th>
                                <th>{{ __('Assurances') }}</th>
                                <th>{{ __('Remarque') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th colspan="9">{{ $enfants->links() }}</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach($enfants as $enfant)
                            <tr>
                                <td>{{ $enfant->lastname }}</td>
                                <td>{{ $enfant->firstname }}</td>
                                <td>{{ $enfant->gender }}</td>
                                <td>{{ \Carbon\Carbon::parse($enfant->birthdate)->format('d/m/Y') }}</td>
                                <td>
                                    @foreach($enfant->tuteurs as $tuteur)
                                    <span class="badge badge-light">{{ $tuteur->fullname }}</span>
                                    @endforeach
                                </td>
                                <td>
                                    @foreach($enfant->users as $user)
                                    <span class="badge badge-light">{{ $user->name }} ({{ $user->service->name }})</span>
                                    @endforeach
                                </td>
                                <td>
                                    @foreach($enfant->assurances as $assurance)
                                    <span class="badge badge-light">{{ $assurance->name }}</span>
                                    @endforeach
                                </td>
                                <td>{{ $enfant->remarque ? __('Oui') : __('Non') }}</td>
                                <td>
                                    <div class="dropdown float-right">
                                        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton{{$enfant->id}}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ __('Actions') }}
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton{{$enfant->id}}">
                                            <a class="dropdown-item" href="{{route('enfants.show', $enfant->id)}}">{{__('Voir')}}</a>
                                            <a class="dropdown-item" href="{{route('enfants.edit', $enfant->id)}}">{{__('Modifier')}}</a>
                                            <div class="dropdown-divider"></div>
                                            @if(auth()->user()->isAdmin() && $enfant->prises->count() > 0)
                                            <a class="dropdown-item" target="_blank" href="{{route('enfants.showPrises', $enfant->id)}}">{{__('Voir les prises')}}</a>
                                            <a class="dropdown-item" target="_blank" href="{{route('enfants.generatePrises', $enfant->id)}}">{{__('Exporter les Prises')}}</a>
                                            <div class="dropdown-divider"></div>
                                            @endif
                                            @if(auth()->user()->isAdmin() && $enfant->rapports->count() > 0)
                                            <a class="dropdown-item" target="_blank" href="{{route('enfants.generateRapports', $enfant->id)}}">{{__('Exporter tout les rapports')}}</a>
                                            <li class="dropdown-submenu">
                                                <a href="#" class="dropdown-item dropdown-toggle"><span class="nav-label">{{__('Les rapports')}}</span><span class="caret"></span></a>
                                                <ul class="dropdown-menu">
                                                    @foreach(array_unique($enfant->rapports->pluck('date')->toArray()) as $date)
                                                    <a class="dropdown-item" target="_blank" href="{{route('enfants.generateRapport', ['enfant' => $enfant->id, 'date' => $date])}}">{{ $date }}</a>
                                                    @endforeach
                                                </ul>
                                            </li>
                                            <!--array_unique($enfant->rapports->pluck('date')->toArray())-->
                                            <div class="dropdown-divider"></div>
                                            @endif
                                            @if($enfant->rdvs->count() > 0)
                                            <a class="dropdown-item" href="{{route('rdvs.showEnfantRdv', $enfant->id)}}">{{__('Voir les rendez-vous')}}</a>
                                            <div class="dropdown-divider"></div>
                                            @endif
                                            @if(auth()->user()->isAdmin())
                                            {{ Form::open([ 'method'  => 'delete', 'route' => [ 'enfants.destroy', $enfant->id ] ]) }}
                                            <a class="dropdown-item delete-model" href="javascript:void(0)">{{__('Supprimer')}}</a>
                                            {{ Form::close() }}
                                            @endif
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/enfant/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    {{ $enfant->fullname }}
                </div>

                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            {!! Form::label('firstname', __('Prénom'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::text('firstname', $enfant->firstname, ['class' => 'form-control', 'readonly' => 'readonly']) !!}
                        </div>
                        <div class="form-group col-md-3">
                            {!! Form::label('lastname', __('Nom'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::text('lastname', $enfant->lastname, ['class' => 'form-control', 'readonly' => 'readonly']) !!}
                        </div>
                        <div class="form-group col-md-3">
                            {!! Form::label('gender', __('Sexe'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::select('gender', ['male' => __('Mâle'), 'female' => __('Femelle') ], $enfant->gender, ['class' => 'form-control', 'disabled' => 'disabled']) !!}
                        </div>
                        <div class="form-group col-md-3">
                            {!! Form::label('birthdate', __('Date de naissance'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::text('birthdate', $enfant->birthdate, ['class' => 'datepicker form-control', 'readonly' => 'readonly']) !!}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            {!! Form::label('tuteurs', __('Tuteurs'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::select('tuteurs[]', App\Tuteur::all(['id', 'firstname', 'lastname'])->pluck('fullname', 'id'), $enfant->tuteurs, ['class' => 'tags form-control', 'disabled' => 'disabled', 'multiple' => 'multiple']) !!}
                        </div>
                        <div class="form-group col-md-4">
                            {!! Form::label('users', __('Suivi par'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::select('users[]', $usersArray, $enfant->users, ['class' => 'tags form-control', 'disabled' => 'disabled', 'multiple' => 'multiple']) !!}
                        </div>
                        <div class="form-group col-md-4">
                            {!! Form::label('assurances', __('Assurances'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::select('assurances[]', App\Assurance::all(['id', 'name'])->pluck('name', 'id'), $enfant->assurances, ['class' => 'tags form-control assurances', 'disabled' => 'disabled', 'multiple' => 'multiple']) !!}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {!! Form::label('diagnostic', __('Diagnostic'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::select('diagnostic_id', App\Diagnostic::all(['id', 'name'])->pluck('name', 'id'), $enfant->diagnostic_id, ['class' => 'form-control', 'disabled' => 'disabled']) !!}
                        </div>
                        <div class="form-group col-md-6">
                            {!! Form::label('docteur', __('Diagnostiqué par'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::select('docteur_id', App\Docteur::all(['id', 'name'])->pluck('name', 'id'), $enfant->docteur_id, ['class' => 'form-control', 'disabled' => 'disabled']) !!}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {!! Form::label('remarque', __('Remarque'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::textarea('remarque', $enfant->remarque, ['class' => 'form-control', 'readonly' => 'readonly']) !!}
                        </div>
                        <div class="form-group col-md-6">
                            {!! Form::label('anamnese', __('Anamnèse'), ['class' => 'col-form-label text-md-right']) !!}
                            {!! Form::textarea('anamnese', $enfant->anamnese, ['class' => 'form-control', 'readonly' => 'readonly']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 prise-options far-options" style="{{ !$enfant->prises()->far()->exists() ? 'display:none;' : '' }}">
            <div class="card">
                <div class="card-header">{{ __('Prises en charge') }}</div>
                <div class="card-body">
                    @foreach($enfant->prises()->far()->get() as $prise)
                        <div class="form-row">
                            <div class="form-group col-3">
                                {!! Form::label('code', __('Code'), ['class' => 'col-form-label text-md-right']) !!}
                                {!! Form::text('code[]', $prise->code, ['class' => 'form-control', 'readonly' => 'readonly']) !!}
                            </div>
                            <div class="form-group col-3">
                                {!! Form::label('charge', __('Charge'), ['class' => 'col-form-label text-md-right']) !!}
                                {!! Form::number('charge[]', $prise->charge, ['class' => 'form-control', 'readonly' => 'readonly']) !!}
                            </div>
                            <div class="form-group col-3">
                                {!! Form::label('month', __('Mois'), ['class' => 'col-form-label']) !!}
                                {!! Form::selectMonth('month', \Carbon\Carbon::parse($prise->date)->month, ['class' => 'mymonthpicker form-control', 'disabled' => 'disabled']) !!}
                            </div>
                            <div class="form-group col-3">
                                {!! Form::label('year', __('Année'), ['class' => 'col-form-label']) !!}
                                {!! Form::selectYear('year', config('app.year'), \Carbon\Carbon::now()->addYears(5)->year, \Carbon\Carbon::parse($prise->date)->year, ['class' => 'myyearpicker form-control', 'disabled' => 'disabled']) !!}
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection