routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::resource('assurances', 'AssuranceController');
    Route::resource('diagnostics', 'DiagnosticController');
    Route::resource('docteurs', 'DocteurController');
    Route::resource('enfants', 'EnfantController');
    Route::resource('prises', 'PriseController');
    Route::resource('services', 'ServiceController');
    Route::resource('tuteurs', 'TuteurController');
    Route::resource('rapports', 'RapportController');
    Route::resource('rdvs', 'RdvController');

    Route::group(['prefix' => 'prises/{prise}'], function () {
        Route::get('generatePdf', 'PriseController@generatePdf')->name('prises.generatePdf');
    });

    Route::post('rapports/generatePdfPerDate', 'RapportController@generatePdfPerDate')->name('rapports.generatePdfPerDate');

    Route::group(['prefix' => 'enfants/{enfant}'], function () {
        Route::get('prises', 'EnfantController@showPrises')->name('enfants.showPrises');
        Route::get('generatePrises', 'EnfantController@generatePrises')->name('enfants.generatePrises');
        Route::get('generateRapports', 'EnfantController@generateRapports')->name('enfants.generateRapports');
        Route::get('generateRapport/{date}', 'EnfantController@generateRapport')->name('enfants.generateRapport');
    });

    Route::group(['prefix' => 'rdvs'], function () {
        Route::get('enfant/{enfant}', 'RdvController@showEnfantRdv')->name('rdvs.showEnfantRdv');
        Route::get('assistant/{user}', 'RdvController@showUserRdv')->name('rdvs.showUserRdv');
    });

    Route::get('rapports/{rapport}/duplicate', 'RapportController@duplicate')->name('rapports.duplicate');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/locales-all.min.js"></script>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.css" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary navbar-laravel">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                        @if (auth()->user()->isAdmin())
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('users.index') }}">{{ __('Utilisateurs') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('assurances.index') }}">{{ __('Assurances') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('diagnostics.index') }}">{{ __('Diagnostics') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('docteurs.index') }}">{{ __('Docteurs') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('enfants.index') }}">{{ __('Enfants') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('prises.index') }}">{{ __('Prises en charge') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('services.index') }}">{{ __('Services') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('tuteurs.index') }}">{{ __('Tuteurs') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('rapports.index') }}">{{ __('Rapports') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('rdvs.index') }}">{{ __('Rendez-vous') }}</a>
                        </li>
                        @elseif (auth()->user()->isAssistant())
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('rapports.index') }}">{{ __('Rapports') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('enfants.index') }}">{{ __('Enfants') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('rdvs.index') }}">{{ __('Rendez-vous') }}</a>
                        </li>
                        @endif
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Se connecter') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('S\'enregistrer') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Se déconnecter') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @component('components.toastr')@endcomponent
</body>
</html>

resources/views/layouts/pdf.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <style>
        body{
            font-family: Arial, Helvetica, sans-serif;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div id="app">
        <header>
            <h1>Header</h1>
        </header>

        <main class="py-4">
            @yield('content')
        </main>

        <footer>
            <h3>Footer</h3>
        </footer>
    </div>
</body>
</html>